name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        bash-version: ['4.4', '5.0', '5.1']
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Bash ${{ matrix.bash-version }}
      run: |
        sudo apt-get update
        sudo apt-get install -y bash=${{ matrix.bash-version }}*
    
    - name: Run tests
      run: ./tests/test.sh
    
    - name: Check code quality
      run: |
        # Check for common issues
        find . -name "*.sh" -exec shellcheck {} \; || true
  
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Lint Shell Scripts
      uses: ludeeus/action-shellcheck@master
      with:
        scandir: './bin ./lib'
        severity: warning